# Generated by Django 3.2.19 on 2023-05-26 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='make_booking',
            old_name='request_space',
            new_name='status',
        ),
    ]
