# Generated by Django 3.2.19 on 2023-05-26 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_rename_make_booking_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='post',
            new_name='workshop',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
    ]
