# Generated by Django 3.2.19 on 2023-05-26 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0006_auto_20230526_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='chef',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Workshop',
        ),
    ]
