# Generated by Django 3.2.19 on 2023-05-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0008_booking_comment_workshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=models.BigIntegerField(default=123456789),
        ),
    ]
