# Generated by Django 3.2.19 on 2023-05-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0009_booking_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='spaces',
            field=models.IntegerField(default=1),
        ),
    ]
