# Generated by Django 3.2.19 on 2023-06-01 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0012_workshop_attendees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='attendees',
        ),
    ]
