# Generated by Django 3.2.20 on 2023-07-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0016_alter_booking_workshop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='spaces',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
