# Generated by Django 3.2.20 on 2023-07-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0017_alter_booking_spaces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='spaces',
            field=models.IntegerField(default=1),
        ),
    ]
