# Generated by Django 3.2.20 on 2023-07-23 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0021_remove_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshops.workshop'),
        ),
    ]
