# Generated by Django 4.2.4 on 2023-08-12 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshops', '0023_alter_booking_workshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshop',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='workshop_attendees', to=settings.AUTH_USER_MODEL),
        ),
    ]
