# Generated by Django 4.2.4 on 2023-08-12 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0024_booking_user_workshop_attendees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user',
            new_name='booked_by',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='attendees',
        ),
    ]
