# Generated by Django 4.2.4 on 2023-08-16 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0024_booking_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
