# Generated by Django 4.2.4 on 2023-09-01 09:36

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Allergy', models.IntegerField(choices=[(0, 'Milk'), (1, 'Egg'), (2, 'Fish'), (3, 'Nuts'), (4, 'Soy')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('description', models.TextField()),
                ('diet', models.IntegerField(choices=[(0, 'Meat'), (1, 'Vegetarian'), (2, 'Pescetarian'), (3, 'Vegan'), (4, 'Nut Allergy')], default=0)),
                ('excerpt', models.TextField(blank=True)),
                ('allergies', models.ManyToManyField(blank=True, to='menu.allergy')),
            ],
        ),
    ]
