# Generated by Django 4.2.4 on 2023-09-01 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allergy',
            old_name='Allergy',
            new_name='allergy',
        ),
    ]
