# Generated by Django 4.2.4 on 2023-09-01 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_rename_allergy_allergy_allergy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pies',
            new_name='Pie',
        ),
    ]
