# Generated by Django 4.2.4 on 2023-09-19 10:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0003_rename_pies_pie'),
    ]

    operations = [
        migrations.AddField(
            model_name='pie',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='pie_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
